---
- name: 'Add "PolicyFileEditor" PowerShell module'
  win_psmodule:
    name: 'PolicyFileEditor'
    state: 'present'

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_DISABLE_CONNECTIONS
- name: 'Ensure users can connect remotely using Remote Desktop Services'
  pauby.windows.win_policyfile:
    path: 'C:\Windows\system32\GroupPolicy\Machine\registry.pol'
    key: 'SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'
    name: 'fDenyTSConnections'
    data: '0'
    type: 'dword'
    state: '{{ "present" if remote_desktop_enabled else "absent" }}'
  notify: 'Restart machine'

- name: 'Ensure firewall is {{ "enabled" if remote_desktop_enabled else "disabled" }} Remote Desktop Services'
  pauby.windows.win_policyfile:
    path: 'C:\Windows\system32\GroupPolicy\Machine\registry.pol'
    key: 'SOFTWARE\Policies\Microsoft\WindowsFirewall\StandardProfile\Services\RemoteDesktop'
    name: 'Enabled'
    data: '1'
    type: 'dword'
    state: '{{ "present" if remote_desktop_enabled else "absent" }}'
  notify: 'Restart machine'

- name: 'Ensure firewall is open for Remote Desktop Services connections from any IP address'
  pauby.windows.win_policyfile:
    path: 'C:\Windows\system32\GroupPolicy\Machine\registry.pol'
    key: 'SOFTWARE\Policies\Microsoft\WindowsFirewall\StandardProfile\Services\RemoteDesktop'
    name: 'RemoteAddresses'
    data: '*'
    type: 'string'
    state: '{{ "present" if remote_desktop_enabled else "absent" }}'
  notify: 'Restart machine'

- name: 'Ensure the Remote Desktop Port is set'
  ansible.windows.win_regedit:
    path: 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
    name: 'PortNumber'
    data: '{{ remote_desktop_port }}'
    type: 'dword'
  notify: 'Restart machine'

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_SECURITY_LAYER_POLICY
- name: 'Ensure the Remote Desktop Services security layer is set'
  pauby.windows.win_policyfile:
    path: 'C:\Windows\system32\GroupPolicy\Machine\registry.pol'
    key: 'SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'
    name: 'SecurityLayer'
    data: '{{ remote_desktop_securitylayer }}'
    type: 'dword'
    state: '{{ "present" if remote_desktop_enabled else "absent" }}'
  notify: 'Restart machine'

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_ENCRYPTION_POLICY
- name: 'Ensure the Remote Desktop Services client connection encryption level is set'
  pauby.windows.win_policyfile:
    path: 'C:\Windows\system32\GroupPolicy\Machine\registry.pol'
    key: 'SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'
    name: 'MinEncryptionLevel'
    data: '{{ remote_desktop_minencryptionLevel }}'
    type: 'dword'
    state: '{{ "present" if remote_desktop_enabled else "absent" }}'
  notify: 'Restart machine'

- name: 'Ensure users / groups are members of "{{ remote_desktop_group }}"'
  ansible.windows.win_group_membership:
    name: '{{ remote_desktop_group }}'
    members: '{{ remote_desktop_members }}'
    state: 'present'
  notify: 'Restart machine'

# https://www.winfaq.de/faq_html/Content/tip1000/onlinefaq.php?h=tip1368.htm
- name: 'Ensure shutdown button is {{ "present" if remote_desktop_enabled and remote_desktop_shutdown_disable else "absent" }} from the Windows Start menu'
  pauby.windows.win_policyfile:
    path: 'C:\Windows\system32\GroupPolicy\User\registry.pol'
    key: 'Software\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    name: 'NoClose'
    data: '1'
    type: 'dword'
    state: '{{ "present" if remote_desktop_enabled and remote_desktop_shutdown_disable else "absent" }}'

# https://www.howtogeek.com/246728/how-to-remove-the-shutdown-button-from-the-windows-login-screen/
- name: 'Ensure shutdown button is {{ "present" if remote_desktop_enabled and remote_desktop_shutdown_disable else "absent" }} from the logion screen'
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
    name: 'shutdownwithoutlogon'
    data: '{{ "0" if remote_desktop_enabled and remote_desktop_shutdown_disable else "1" }}'
    type: 'dword'