galaxy_info:
  author: 'Paul Broadwith'
  description: 'Manages the Windows Start Menu and Taskbar layout.'

  issue_tracker_url: 'https://github.com/pauby/ansible_collection.windows/issues'

  license: MIT

  min_ansible_version: 2.9

  # https://galaxy.ansible.com/api/v1/platforms/
  platforms:
  - name: 'windows'
    versions:
      - 10
      - 2019

  galaxy_tags:
    - 'windows'
    - 'start menu'
    - 'taskbar'